### ISSUE TITLE
Community site roadmap

### ISSUE THREAD

**Issue by Kenny477** [leofuturer/eDrops3#39]
#### Posts/projects
- [ ] Delete/edit posts and projects
- [ ] Rich text editing instead of just plaintext
- [ ] Reference projects in posts and vice-versa

#### New features
- [ ] Announcements page
- [ ] Literature aggregator (collect recent papers on EWOD)
