### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by Kenny477** [leofuturer/eDrops3#88]
# Roadmap

A "todo list" for improvements to the app.

## Frontend

Some general improvements to our frontend and how it interacts with the backend.

- [ ] **Better integration with Shopify**
Right now checkout opens in a new tab, and also a lot of our data fetching from Shopify is duplicated to our own backend. Maybe have Shopify manage cart/orders and our backend only manage user information and features like assigning orders to foundry workers, etc.
Something worth looking into is https://hydrogen.shopify.dev/. Hydrogen is a React-based framework that is catered towards custom Shopify storefronts. Has components/integrations for managing cart/products.
An alternative would be figuring out how to use the Shopify Buy Button SDK to embed checkout in our own site.
- [ ] **Better reactivity**
Look into using something like https://react-query-v3.tanstack.com/ to better load/sync data from backend.
- [ ] **Unit testing**
Already added Cypress to our frontend, but haven't implemented many tests. Implement tests so we don't have to manually check things everytime we add features. Will save a lot of hassle when going over PRs.

#### Related Issues
- #83 
- #76 

## Backend

- [ ] **Clean up code**
Code needs a lot of cleanup. Certain endpoints are never used (i.e. generated but not accessed). And names of endpoints are not very standardized. We should try to use common naming conventions like simply sending a POST request to /users instead of having a specific endpoint for /users/signup when we want to add a user.
Also need to cleanup ecommerce site related models (i.e. OrderInfo, etc.) as there may be fields that aren't necessary.
- [ ] **Authorization**
Need to implement something like RBAC to prevent users from accessing resources they shouldn't have access to. Loopback doesn't have very good documentation on this and as it is pretty much not maintained, we may need to push this off until there is another framework worth migrating to.
- [ ] **Better authentication/cookie management**
This is more of a minor issue that only pertains to XSS attacks (see https://edrops-website.gitbook.io/edrops3/miscellaneous/security) that isn't very likely. But setting cookies server-side as httpOnly will prevent cookies containing user information from being revealable on the client.

#### Related Issues
- #15 
- #73
